spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/case_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:${MYSQL_USER:root}}
    password: ${DB_PASSWORD:${MYSQL_ROOT_PASSWORD:Mouna@182}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
