package com.misxmatch.notification.service;

import jakarta.mail.internet.MimeMessage;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import java.util.List;

@Slf4j
@Service
public class EmailServiceImpl implements EmailService {

    @Autowired(required = false)
    private JavaMailSender mailSender;

    @Value("${smtp.from:no-reply@misxmatch.org}")
    private String fromEmail;

    @Value("${smtp.enabled:false}")
    private boolean smtpEnabled;

    @Value("${spring.mail.host:}")
    private String smtpHost;

    @Value("${spring.mail.username:}")
    private String smtpUser;

    @Override
    public void sendEmail(String to, String subject, String body, boolean isHtml) {
        if (to == null || to.isBlank()) {
            log.warn("Email recipient 'to' is empty; skipping email dispatch.");
            return;
        }

        boolean canSendRealEmail = smtpEnabled || (mailSender != null && smtpHost != null && !smtpHost.isBlank() && !smtpHost.contains("localhost"));

        if (!canSendRealEmail) {
            log.info("[EmailService - Dev No-Op Fallback] To: '{}' | Subject: '{}' | Body Snippet: '{}' (SMTP host/credentials not configured; set SMTP_HOST in env for live sending).",
                    to, subject, body != null && body.length() > 80 ? body.substring(0, 80) + "..." : body);
            return;
        }

        try {
            if (isHtml) {
                MimeMessage message = mailSender.createMimeMessage();
                MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
                helper.setFrom(fromEmail);
                helper.setTo(to);
                helper.setSubject(subject);
                helper.setText(body, true);
                mailSender.send(message);
            } else {
                SimpleMailMessage message = new SimpleMailMessage();
                message.setFrom(fromEmail);
                message.setTo(to);
                message.setSubject(subject);
                message.setText(body);
                mailSender.send(message);
            }
            log.info("Email successfully sent to '{}' with subject '{}'.", to, subject);
        } catch (Exception e) {
            log.error("Failed to send real email to '{}': {}", to, e.getMessage(), e);
        }
    }

    @Override
    public void sendEmergencyBroadcast(String caseNumber, String personName, String priority, String location, String details, List<String> recipients) {
        String subject = String.format("🚨 [%s EMERGENCY ALERT] Missing Person Case #%s - %s", priority != null ? priority.toUpperCase() : "CRITICAL", caseNumber, personName);
        String bodyHtml = String.format("""
                <div style="font-family: Arial, sans-serif; padding: 20px; border: 2px solid #e53e3e; border-radius: 8px; max-width: 600px;">
                    <h2 style="color: #c53030; margin-top: 0;">🚨 HIGH PRIORITY EMERGENCY BROADCAST</h2>
                    <p><strong>Case Number:</strong> #%s</p>
                    <p><strong>Missing Person:</strong> %s</p>
                    <p><strong>Priority Level:</strong> <span style="color: #c53030; font-weight: bold;">%s</span></p>
                    <p><strong>Last Known Location:</strong> %s</p>
                    <p><strong>Case Summary:</strong> %s</p>
                    <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
                    <p style="font-size: 12px; color: #718096;">This is an automated emergency broadcast generated by the MISXMATCH Reunification Platform. Immediate action or patrol dispatch required by assigned authorities.</p>
                </div>
                """, caseNumber, personName, priority != null ? priority.toUpperCase() : "CRITICAL", location != null ? location : "Unknown Location", details != null ? details : "Active investigation underway.");

        List<String> targetRecipients = (recipients != null && !recipients.isEmpty()) ? recipients : List.of("police_hq@misxmatch.org", "admin@misxmatch.org");
        for (String recipient : targetRecipients) {
            sendEmail(recipient, subject, bodyHtml, true);
        }
    }
}
